import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2B2B2B',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
    backgroundColor: '#2B2B2B',
  },
  logo: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#D4AF37',
  },
  menuButton: {
    padding: 10,
  },
  menuBar: {
    width: 25,
    height: 3,
    backgroundColor: '#D4AF37',
    marginVertical: 3,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 15,
  },
  activityCard: {
    backgroundColor: '#3A3A3A',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    borderWidth: 3,
    borderColor: '#5A5A3A',
  },
  sectionTitle: {
    color: '#6B9BD1',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  graphContainer: {
    height: 100,
    backgroundColor: '#2B2B3B',
    borderRadius: 10,
    marginBottom: 10,
    position: 'relative',
  },
  graphLine: {
    flex: 1,
    position: 'relative',
  },
  graphDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#6B9BD1',
    position: 'absolute',
    top: 20,
    left: '5%',
  },
  activityLabels: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  activityLabel: {
    color: '#888',
    fontSize: 10,
  },
  bottomSection: {
    flexDirection: 'row',
    marginBottom: 15,
    gap: 10,
  },
  progressionCard: {
    flex: 1,
    backgroundColor: '#4A4A2A',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
  },
  circleContainer: {
    marginBottom: 10,
  },
  outerCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: '#E85D75',
    justifyContent: 'center',
    alignItems: 'center',
  },
  middleCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 5,
    borderColor: '#D4AF37',
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 5,
    borderColor: '#6B9BD1',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  circleText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  circleSubtext: {
    color: '#FFF',
    fontSize: 14,
    marginTop: 8,
  },
  progressionTitle: {
    color: '#D4AF37',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  barChartContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'baseline',
    width: '100%',
    height: 80,
  },
  barWrapper: {
    alignItems: 'center',
    flex: 1,
  },
  bar: {
    width: 12,
    backgroundColor: '#D4AF37',
    borderRadius: 3,
  },
  barLabel: {
    color: '#888',
    fontSize: 10,
    marginTop: 5,
  },
  taskCard: {
    flex: 1.5,
    backgroundColor: '#4A4A2A',
    borderRadius: 15,
    overflow: 'hidden',
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#3A3A1A',
    padding: 10,
  },
  taskHeaderText: {
    color: '#D4AF37',
    fontSize: 12,
    fontWeight: 'bold',
  },
  taskHeaderIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmark: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  taskList: {
    maxHeight: 200,
    padding: 10,
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  taskCheckbox: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#4CAF50',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskCheckboxCompleted: {
    backgroundColor: '#4CAF50',
  },
  taskCheck: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  taskText: {
    color: '#CCC',
    fontSize: 11,
    flex: 1,
  },
  taskTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#888',
  },
  taskFooter: {
    backgroundColor: '#3A3A1A',
    padding: 15,
  },
  taskFooterText: {
    color: '#D4AF37',
    fontSize: 10,
    textAlign: 'center',
    lineHeight: 14,
  },
  topActivitiesSection: {
    marginBottom: 15,
  },
  topActivitiesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#3A3A2A',
    padding: 15,
    borderRadius: 10,
  },
  topActivitiesTitle: {
    color: '#D4AF37',
    fontSize: 14,
    fontWeight: 'bold',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#D4AF37',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonText: {
    color: '#2B2B2B',
    fontSize: 24,
    fontWeight: 'bold',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 20,
    marginBottom: 20,
  },
  navButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#D4AF37',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeIcon: {
    width: 30,
    height: 30,
  },
  homeIconRoof: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#2B2B2B',
  },
  homeIconBase: {
    width: 20,
    height: 15,
    backgroundColor: '#2B2B2B',
    marginLeft: 5,
  },
  editIcon: {
    width: 30,
    height: 30,
    position: 'relative',
  },
  editIconSquare: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#2B2B2B',
    position: 'absolute',
    bottom: 0,
    left: 5,
  },
  editIconPencil: {
    width: 15,
    height: 3,
    backgroundColor: '#2B2B2B',
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    top: 0,
    right: 0,
  },
});